### ISSUE TITLE
双击搜索输入框之后弹出报错提示，无法再次进入输入框，按esc，再按两次gi，才能重新进入

### ISSUE THREAD

**Issue by abtxu** [brookhong/Surfingkeys#1833] opened 2022-09-12 21:44 UTC
![image](https://user-images.githubusercontent.com/48761002/189764017-57eb2579-ceb4-4085-b9a7-e4cbf0cdc87b.png)

**Comment by Imymirror** [comment] 2022-09-26 19:39
(probably) Duplicate of https://github.com/brookhong/Surfingkeys/issues/1800

**Closed** 2022-11-09 02:55 UTC
