### ISSUE TITLE
getKeyChar: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by andys8** [brookhong/Surfingkeys#789] opened 2018-07-06 14:29 UTC
### Issue

I'm getting an exception. The plugin is disabled for localhost (ALT + S). I think it has to to with autofilled fields from the browser and losing focus. I'm sorry, I can't give more information here.

```
common_content.min.js:1 Uncaught TypeError: Cannot read property 'length' of undefined
    at Object.t.getKeyChar (common_content.min.js:1)
    at common_content.min.js:1
t.getKeyChar @ common_content.min.js:1
(anonymous) @ common_content.min.js:1
common_content.min.js:1 Uncaught TypeError: Cannot read property 'length' of undefined
    at Object.t.getKeyChar (common_content.min.js:1)
    at common_content.min.js:1
t.getKeyChar @ common_content.min.js:1
(anonymous) @ common_content.min.js:1
```

#### Investigation

Looking at the code there is a call of `.length`, on an uninitialized `var`.

https://github.com/brookhong/Surfingkeys/blob/d972b5bb5b3171a9caa5ea570b204107ac9d4a7e/content_scripts/keyboardUtils.js#L136-L138

**Comment by brookhong** [comment] 2018-07-08 02:06
This is strange, `character` is always initialized https://github.com/brookhong/Surfingkeys/blob/master/content_scripts/keyboardUtils.js#L90 .

Could you provide the steps to reproduce this issue?

**Comment by andys8** [comment] 2018-07-08 13:19
It is mutated a bunch of times and there is the chance of it being `undefined` or `null`. And this is actually the case.

### Reproduce the issue

It is potentially hard for you to reproduce the issue. I'm using the current chrome browser, and the current plugin.

1. Open <https://hecrj.github.io/composable-form/#/login>
2. Login with random data (nothing will happen because it's a demo)
3. Make chrome remember the credentials
4. Reload the page, chrome will fill out the fields
5. Loose the focus of the field by clicking somewhere on the background
6. The error will be visible in the console

### Investigation

It looks like there is a `keydown` event without the `key` field.
![image](https://user-images.githubusercontent.com/13085980/42420188-2d9aab94-82c2-11e8-8b8d-a724b6193543.png)

**Comment by jpsala** [comment] 2018-08-08 16:54
Hi, is there a fix for this?
As a dev it's annoying to see this error, because always seems to be from mine :)
Thanks!

**Closed** 2018-11-04 15:03 UTC
