### ISSUE TITLE
Mode Insert pushed into mode stack again.

### ISSUE THREAD

**Issue by yet-another-tim** [brookhong/Surfingkeys#1805] opened 2022-08-23 09:54 UTC
## Error details

Modes in stack: Insert,Insert,Normal,Normal

SurfingKeys: 1.0.7

Chrome: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.102 Safari/537.36

URL: https://ibe2.rex.com.au/Details

## Context

I clicked on a form and the SurfingKeys error bar came up. Focus went away from form.

**Comment by brookhong** [comment] 2022-08-23 15:27
duplicate of #1800

**Closed by brookhong** 2022-08-23 15:27 UTC
