### ISSUE TITLE
Unrecognized key event: <Process>

### ISSUE THREAD

**Issue by songqii** [brookhong/Surfingkeys#199] opened 2017-01-18 15:27 UTC
## Error details

{
    "metaKey": false,
    "altKey": false,
    "ctrlKey": false,
    "shiftKey": false,
    "keyCode": 229,
    "code": "Digit6",
    "composed": true,
    "key": "Process"
}

SurfingKeys: 0.7.1

Chrome: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36

## Context

**Please replace this with a description of how you were using SurfingKeys.**

**Comment by aspiers** [comment] 2017-01-18 16:20
This is a duplicate of #198 and can be closed.

**Comment by brookhong** [comment] 2017-01-19 11:09
Thanks, fixed in 0.7.2

**Closed by brookhong** 2017-01-19 11:09 UTC
