### ISSUE TITLE
browser broken

### ISSUE THREAD

**Issue by alejandrobabio** [brookhong/Surfingkeys#1835] opened 2022-09-14 15:22 UTC
## Error details

SurfingKeys: 1.0.8

Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36

URL: <The_URL_Where_You_Find_The_Issue>

## Context

This image appears:
![image](https://user-images.githubusercontent.com/1581649/190196224-f5f5663b-f6f6-49fd-b627-0a9c39415e54.png)
And I need to restore the page to continue working.

**Comment by andreas-venturini** [comment] 2022-09-26 09:52
Duplicate of https://github.com/brookhong/Surfingkeys/issues/1800

**Closed** 2022-11-12 14:46 UTC
