### ISSUE TITLE
Support for FireFox Quantum

### ISSUE THREAD

**Issue by phillipwei** [brookhong/Surfingkeys#574] opened 2017-11-16 17:19 UTC
Hi! I would love to be able to use this in FireFox Quantum.

**Comment by Stvad** [comment] 2017-11-18 19:04
's a duplicate of https://github.com/brookhong/Surfingkeys/issues/329

**Comment by brookhong** [comment] 2017-11-26 04:04
https://addons.mozilla.org/en-US/firefox/addon/surfingkeys_ff/

0.9.15 released for Firefox, closed this.

**Closed by brookhong** 2017-11-26 04:04 UTC

**Comment by zzxqd** [comment] 2017-12-07 08:28
is it had closed?why can't i search on https://addons.mozilla.org/en-US/firefox/addon/surfingkeys_ff/  it show that :Page not found
