### ISSUE TITLE
Surfingkeys does not work with my "AZERTY" keyboad layout

### ISSUE THREAD

**Issue by poirelpa** [brookhong/Surfingkeys#1] opened 2015-09-07 08:21 UTC
Hi !

I am using an "AZERTY" (french) keyboard layout and the mappings do not work the way they should.

e.g. The "/" on an "AZERTY" keyboard is SHIFT+":"
The search bar does not appear when I press SHIFT + ":" but it appears when I press ":"

Thanks for your work !

Paul

**Comment by brookhong** [comment] 2015-09-07 10:36
Thanks.

I pushed a fix on `dev` branch, could you try it by loading an unpacked extension? And let me know if it works, as I have no AZERTY keyboard to verify.

**Comment by brookhong** [comment] 2015-09-07 10:36
f

**Closed** 2015-12-04 15:47 UTC

**Comment by calops** [comment] 2021-09-20 13:12
Hi, I also use an AZERTY keyboard and the issue is still present today. It's also behaving exactly the same way in cVim. I suspect non-qwerty layouts don't work at all.
