### ISSUE TITLE
Mode Insert pushed into mode stack again.

### ISSUE THREAD

**Issue by gabrielqv** [brookhong/Surfingkeys#181] opened 2017-01-07 15:34 UTC
## Error details

Modes in stack: Disabled,Insert,Normal

## Context

**I was writing normally in a forum I probably used copy and paste, I interrupted my work for 20 minutes, and the page became unresponsive, I disable surfingkeys trying to solve it and the error appeared **

**Comment by aspiers** [comment] 2017-01-08 11:36
Yes, I see this too - I think it's a duplicate of #178.  It's not good that this happens even when Surfingkeys is disabled :-/

**Comment by brookhong** [comment] 2017-01-08 16:48
Should be fixed in 0.7.0

It is just caused by Disabled mode, please verify it, and kindly let me if it works.

**Comment by aspiers** [comment] 2017-01-08 20:19
Seems OK now, thanks.

**Closed** 2017-01-09 00:57 UTC
