### ISSUE TITLE
Unable to view online pdf with PDF viewer disabled

### ISSUE THREAD

**Issue by gyli** [brookhong/Surfingkeys#1126] opened 2020-01-06 19:05 UTC
## Error details

SurfingKeys: 0.9.56

Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36

## Context

When opening online pdf file, the webpage would only display gray background color but not showing any content with PDF viewer disabled. Once PDF viewer is enabled, it's back to normal displaying the file through PDF viewer.

**Comment by brookhong** [comment] 2020-01-08 15:07
Fixed in 0.9.57, please have a try. Duplicate of #1119

**Closed by brookhong** 2020-01-08 15:08 UTC
