### ISSUE TITLE
Mode Insert pushed into mode stack again.

### ISSUE THREAD

**Issue by L1Q** [brookhong/Surfingkeys#1840] opened 2022-09-23 01:50 UTC
## Error details

Modes in stack: Insert,Insert,Normal,Normal

SurfingKeys: 1.0.8

Chrome: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36

URL: https://github.com/hteumeuleu/caniemail/issues/new

## Context

Clicking text input fields on GitHub, clicking with my mouse, that is.

**Comment by Imymirror** [comment] 2022-09-26 19:40
(probably) Duplicate of https://github.com/brookhong/Surfingkeys/issues/1800

**Closed** 2022-11-02 05:42 UTC
