### ISSUE TITLE
Mode Insert pushed into mode stack again.

### ISSUE THREAD

**Issue by goodcoderfromeurope** [brookhong/Surfingkeys#1838] opened 2022-09-16 07:58 UTC
## Error details

Modes in stack: Insert,Insert,Normal,Normal

SurfingKeys: 1.0.8

Chrome: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36

URL: https://www.olx.pl/d/adding/edit/753634221/?bs=olx_pro_listing

## Context

**Please replace this with a description of how you were using SurfingKeys.**

**Comment by Imymirror** [comment] 2022-09-26 19:40
(probably) Duplicate of https://github.com/brookhong/Surfingkeys/issues/1800

**Closed** 2022-11-02 05:42 UTC
