### ISSUE TITLE
Mode Insert pushed into mode stack again.

### ISSUE THREAD

**Issue by lcx412** [brookhong/Surfingkeys#1834] opened 2022-09-13 14:38 UTC
## Error details

Modes in stack: Insert,Insert,Normal,Normal

SurfingKeys: 1.0.8

Chrome: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36

URL: https://portal.bjt.beijing.gov.cn/p/login/login.html?pubKey=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCma7eAurjGbzgBjvVth4hbm4QmacBcUnk7v6geN9WD7lfiJ3MvGidtB7Tj94v6pgtSAqzY7//f1gGieuTOjbA4+Gza0h3IFIWkLj9+ZLZqm9VeHrD+Ixty7E1OVF2TsvwwREJvqcM/KUPZkdhccku0aY1Np60zp/eqO011VaLFowIDAQAB

## Context

**Please replace this with a description of how you were using SurfingKeys.**

**Comment by Imymirror** [comment] 2022-09-26 19:41
(probably) Duplicate of https://github.com/brookhong/Surfingkeys/issues/1800

**Closed** 2022-11-02 05:42 UTC
