### ISSUE TITLE
Firefox 72.0b1 无限自动刷新页面

### ISSUE THREAD

**Issue by McGiRG3z** [brookhong/Surfingkeys#1087] opened 2019-12-03 18:24 UTC
刚更新Firefox Beta至最新版72.0b1，该扩展会导致任何网页都无限自动刷新。请开发者核查。

**Comment by Stvad** [comment] 2019-12-03 23:18
I believe it's a duplicate of https://github.com/brookhong/Surfingkeys/issues/1076

**Comment by brookhong** [comment] 2019-12-04 03:45
Fixed in 0.9.55

**Closed by brookhong** 2019-12-04 03:45 UTC
