### ISSUE TITLE
Surfingkeys constantly refreshes on Firefox Nightly 72

### ISSUE THREAD

**Issue by gibfahn** [brookhong/Surfingkeys#1076] opened 2019-11-13 13:34 UTC
## Error details

SurfingKeys: 0.9.53

Browser: Firefox Nightly 72.0a1 20191112094307 - macOS 10.15.1

URL: any

## Context

I'm unsure whether this is a Firefox issue or a Surfingkeys issue, but I recently restarted Firefox and suddenly every page started reloading every ~4 seconds. I see the following errors in the console:

![image](https://user-images.githubusercontent.com/15943089/68763129-a0300880-060f-11ea-8f1b-ff4d2ee2493a.png)

**Comment by yav334** [comment] 2019-11-14 05:20
Same issue running Surfingkeys 0.9.53 under Firefox Nightly 72.0a1 on the Debian Testing distro.   Still works fine with distribution's Chromium browser.
  
> uname -a                                                                     
Linux  xyz 5.2.0-3-amd64 #1 SMP Debian 5.2.17-1 (2019-09-26) x86_64 GNU/Linux

**Comment by beanaroo** [comment] 2019-11-17 19:51
I can confirm the behaviour started after upgrading this weekend.

Firefox Nightly 72.0a1.20191117 on Arch Linux

Unfortunately this also affects the settings page, making it difficult to try finding a workaround.

**Comment by vonHabsi** [comment] 2019-12-03 14:42
I' am also having the same problem after upgrading to 72.0beta1

**Comment by vonHabsi** [comment] 2019-12-03 16:43
According to a response from reddit - [Surking Keys is broken in Firefox 72 : firefox](https://old.reddit.com/r/firefox/comments/e5iem4/surking_keys_is_broken_in_firefox_72/) the problem is caused by https://bugzilla.mozilla.org/show_bug.cgi?id=1594710 and needs to be fixed by @brookhong

**Comment by Stvad** [comment] 2019-12-03 23:19
using Firefox developer edition - it got recently updated to 72.0b1. And it's constantly reloading all the pages now :(

**Closed** 2019-12-04 03:40 UTC

**Comment by brookhong** [comment] 2019-12-04 03:44
Thanks guys.

Fixed in 0.9.55
