### ISSUE TITLE
控制台报错

### ISSUE THREAD

**Issue by CircleFaith** [brookhong/Surfingkeys#1799] opened 2022-08-19 15:56 UTC
## Error details

Error handling response: TypeError: Cannot read properties of undefined (reading 'indexOf')
    at <URL>

![image](https://user-images.githubusercontent.com/49904250/185658159-b1e67bf1-98d5-4296-b096-d0275e9a28a7.png)

SurfingKeys: 1.0.7

Chrome: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36

**Comment by brookhong** [comment] 2022-08-19 17:00
duplicate of #1798

**Closed by brookhong** 2022-08-19 17:00 UTC
