### ISSUE TITLE
Ability to switch between background and foreground tab on link open

### ISSUE THREAD

**Issue by paradox460** [brookhong/Surfingkeys#417] opened 2017-07-18 17:29 UTC
This is a minor implementation detail I miss from cVim/Vimium. In both plugins, if you hit `f` or whatever you have bound to trigger link hints, you can switch the mode of the link open by holding shift. 

So if you have `f` bound to open the link in a new tab in the foreground, and the link hint was `aa`, you could type `aA` and the link would open as if you had entered link hint mode in background mode; that is to say, the link opens without changing focus

**Comment by brookhong** [comment] 2017-07-19 02:31
Please see https://github.com/brookhong/Surfingkeys/commit/612e1f2370d7c15d839443c12a8979532258adf2

This has been released in 0.8.9, are you using 0.8.9 -- the latest release?

**Comment by paradox460** [comment] 2017-07-20 02:10
I appear to have been running the latest, and it does work, so maybe my memory of how cVim worked was faulty. I'd love if I could switch it so it opens the link in a new, background (inactive) tab, similar to how `C` works with the default binds

**Comment by j-hui** [comment] 2020-02-21 17:43
Circling back to this, because it looks like the issue is not yet closed. I'm still encountering this issue on FF 73.01. Holding shift launches the link in a new tab, but it's active, switching focus away. Right now it seems the only way to open a new tab in the background is to do what @paradox460 suggests and use `C`. The slightly weird thing about that is that if you use `C`, and then type the last character in capitalized, it'll still open the link in a new active tab.

I've dug around a little bit and here's what I've found. [`hints.js`](
https://github.com/brookhong/Surfingkeys/blob/master/content_scripts/hints.js) has since changed quite a bit since `612e1f2` – so perhaps this issue should be closed and I could file a new one.

But in any ca,se I'm currently seeing [this condition](https://github.com/brookhong/Surfingkeys/blob/77f21db046e2cb842f5cb737eda869fcf385c4fb/content_scripts/hints.js#L588):

```javascript
if (shiftKey && window.navigator.userAgent.indexOf("Firefox") !== -1) { // mouseButton does not work for firefox in mouse event.
    tabbed = true;
    active = true;
}
```

Not entirely sure what the comment means, but the blame on this line was from [0.9.28](https://github.com/brookhong/Surfingkeys/commit/cbf7a011bbb97a5b1d97c62db45ab84340171234) referencing #671 and #685.

This overrides `active`, which is taken from `behaviours.active`. I'm not familiar enough with this extension or FF extension development in general to comment on what this entails, but I'm wondering if this is something worth looking into fixing? I'm happy to contribute.

**Closed** 2021-03-22 11:37 UTC
