### ISSUE TITLE
Error in console: DevTools failed to load source map

### ISSUE THREAD

**Issue by beisu** [brookhong/Surfingkeys#1529] opened 2021-08-18 03:27 UTC
![image](https://user-images.githubusercontent.com/11241488/129832216-bef6dac6-fa22-4737-b03e-c073894b6fbb.png)

**Comment by aspiers** [comment] 2021-08-23 13:58
I noticed this too, it's spamming DevTools console a lot :-(

**Comment by aspiers** [comment] 2021-11-13 14:55
This is a duplicate of #1260, and PR #1261 fixes it.

**Comment by brookhong** [comment] 2022-01-16 03:40
Should have been fixed in 1.0.

**Closed by brookhong** 2022-01-16 03:40 UTC
